<a href="https://colab.research.google.com/github/DrMiracle/Colab-Projects/blob/main/LevenshteinDistance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def levenshtein_distance(word1: str, word2: str, return_table: bool=True):
  '''
  Compute the Levenshtein distance between 2 words
  :param word1: first word
  :param word2: second word
  :param return_table: whether to return the full table; defaults to True
  :returns: the distance itself, as well as (possibly) the table
  '''

  table = np.zeros((len(word1) + 1, len(word2) + 1))
  table[:, 0] = range(len(word1) + 1)
  table[0, :] = range(len(word2) + 1)

  for i in range(len(word1)):
    for j in range(len(word2)):
      table[i + 1, j + 1] = min(table[i, j + 1], table[i + 1, j], table[i, j]) + 1
      if word1[i] == word2[j]:
        table[i + 1, j + 1] = min(table[i + 1, j + 1], table[i, j])

  if return_table:
    return table[len(word1), len(word2)], table

  return table[len(word1), len(word2)]

In [ ]:
word1 = 'renaissance'
word2 = 'reconnaissance'

In [ ]:
dist, table = levenshtein_distance(word1, word2)

In [ ]:
dist

3.0

In [ ]:
print(table)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
 [ 1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 2.  1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
 [ 3.  2.  1.  1.  2.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 4.  3.  2.  2.  2.  3.  3.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 5.  4.  3.  3.  3.  3.  4.  4.  3.  4.  5.  6.  7.  8.  9.]
 [ 6.  5.  4.  4.  4.  4.  4.  5.  4.  3.  4.  5.  6.  7.  8.]
 [ 7.  6.  5.  5.  5.  5.  5.  5.  5.  4.  3.  4.  5.  6.  7.]
 [ 8.  7.  6.  6.  6.  6.  6.  5.  6.  5.  4.  3.  4.  5.  6.]
 [ 9.  8.  7.  7.  7.  6.  6.  6.  6.  6.  5.  4.  3.  4.  5.]
 [10.  9.  8.  7.  8.  7.  7.  7.  7.  7.  6.  5.  4.  3.  4.]
 [11. 10.  9.  8.  8.  8.  8.  8.  8.  8.  7.  6.  5.  4.  3.]]
