<a href="https://colab.research.google.com/github/DrMiracle/Colab-Projects/blob/main/data%20analysis/ex%207.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import scipy.stats
import statsmodels as sm
from scipy.stats import kstest, ksone, chisquare, stats, normaltest

#1 пункт
samples = []
for i in range(200):
  samples.append(np.random.uniform(0, 1, size=100))
print(np.array(samples)[:5,:5])

#2 пункт
ks = np.array([kstest(sample, 'uniform') for sample in samples])
print(sum(ks[:,1] < 0.05))

#3 пункт
kolmogorov_passed = False
zeta = samples[0]
std = np.std(zeta)
mu = 0.5
p_val_kolmogorov = kstest(zeta, 'norm', args=(mu, std))[1]

if p_val_kolmogorov > 0.05:
    print("Minimal n for Kolmogorov's test: 1")
    kolmogorov_passed = True

for i in range(1, 200):
    zeta = zeta + samples[i]
    mu = (i+1)/2
    std = np.std(zeta)
    p_val_kolmogorov = kstest(zeta, 'norm', args=(mu, std))[1]
    if (not kolmogorov_passed) and p_val_kolmogorov > 0.05:
        print("Minimal n for Kolmogorov's test: ", i+1)
        kolmogorov = True
        break

#4 пункт
pearson_passed = False
zeta = samples[0]
std = np.std(zeta)
mu = 0.5
p_val_pearson = normaltest(zeta)[1]

if p_val_pearson > 0.05:
    print("Minimal n for Pearson's test: 1")
    pearson_passed = True

for i in range(1, 200):
    zeta = zeta + samples[i]
    mu = (i+1)/2
    std = np.std(zeta)

    p_val_pearson = normaltest(zeta)[1]
    if (not pearson_passed) and p_val_pearson > 0.05:
        print("Minimal n for Pearson's test: ", i+1)
        pearson = True
        break

[[0.12553961 0.78821642 0.73122633 0.96478567 0.00701734]
 [0.43912533 0.82848912 0.62415019 0.08507679 0.66170283]
 [0.34543689 0.33067598 0.90311915 0.86359801 0.89853899]
 [0.13669439 0.99387562 0.7575469  0.09214971 0.81796935]
 [0.1299906  0.00391354 0.20286474 0.33026873 0.58488701]]
13
Minimal n for Kolmogorov's test: 1
Minimal n for Pearson's test:  2
